version: '3'
services:
  server:
    build: ./server
    ports:
      - 3001:3001
    volumes:
      - ./server:/usr/src/app
    command: npm run start
  client:
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client:/usr/src/app
    command: npm run start